sudo: false
language: node_js
node_js:
  - "5"

cache:
  directories:
    - $(npm config get prefix)/bin/typings
    - node_modules

install:
  - npm install typings -g
  - npm install

script:
  - npm run test
  - npm run dist
